### ISSUE TITLE
Empty fields in HTML in Safari 10.1.1 for Mac (probably caused by Javascript error)

### ISSUE THREAD

**Issue by wilfreddijksman** [circlecell/randomkeygen.com#2]
When I visit [rondomkeygen.com](https://randomkeygen.com) with Safari 10.1.1 for Mac all fields are empty. Even when I click on "Generate a New Set of Random Passwords and Keys" or disable all my plugins. In the developer portal I see the following Javascript error:
`SyntaxError: Cannot declare a let variable twice: 'b'.`

**User agent:**
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4`

See also attached image.

![schermafbeelding 2017-06-01 om 14 30 56](https://cloud.githubusercontent.com/assets/1773594/26679828/04ee6c58-46d7-11e7-930c-936737ccf5ab.png)

**Comment by finom** [comment]
@wilfreddijksman thank you.

**Comment by finom** [comment]
Fixed now. Thank you again.
